spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/queueforge}
    username: ${SPRING_DATASOURCE_USERNAME:queueforge}
    password: ${SPRING_DATASOURCE_PASSWORD:queueforge}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    com.zaxxer.hikari: INFO
    org.hibernate.SQL: INFO
